### ISSUE TITLE
Start throws exception

### ISSUE THREAD

**Issue by colorizedmind** [thenativeweb/wolkenkit-console#8]
When starting wolkenkit-console the following exception is thrown. I also changed the current working directory to a Node project directory with a package.json and tried it again with the same result.

```
$ wolkenkit-console
C:\Users\Henning\AppData\Roaming\nvm\v8.9.1\node_modules\wolkenkit-console\node_modules\flaschenpost\dist\readPackageJson.js:16
    throw new Error('Could not find package.json.');
    ^
 
Error: Could not find package.json.
    at readPackageJson (C:\Users\Henning\AppData\Roaming\nvm\v8.9.1\node_modules\wolkenkit-console\node_modules\flaschenpost\dist\readPackageJson.js:16:11)
    at Object.flaschenpost.initialize (C:\Users\Henning\AppData\Roaming\nvm\v8.9.1\node_modules\wolkenkit-console\node_modules\flaschenpost\dist\flaschenpost.js:23:36)
    at Object.<anonymous> (C:\Users\Henning\AppData\Roaming\nvm\v8.9.1\node_modules\wolkenkit-console\node_modules\flaschenpost\dist\flaschenpost.js:111:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

### Steps to reproduce

* Install wolkenkit-console with `npm install -g wolkenkit-console`
* Start wolkenkit-console with `wolkenkit-console`

### Expected result

* The application starts a local web server with wolkenkit-console

### Actual result

* An exception is thrown

**Comment by goloroden** [comment]
Hi @colorizedmind 😊 

Thanks for bringing up this issue!

I tried to reproduce it, but on my machine everything works as expected. I fear that this is an issue related to Windows, so we will need to have a closer look at this.

Meanwhile, you may use https://console.wolkenkit.io as a workaround, which is a hosted version of the very same tool.

**Comment by goloroden** [comment]
@grundhoeferj Can you please have a look at this, and try to reproduce this on Windows?

**Comment by colorizedmind** [comment]
@goloroden @grundhoeferj Maybe the exception is related to [this issue](https://github.com/inxilpro/node-app-root-path/issues/20)?

**Comment by goloroden** [comment]
Yes … now that you linked that issue I remember that we already had problems with this before on Windows. Maybe we need to come up with an alternative package, which does work even on Windows…

**Comment by grundhoeferj** [comment]
Hey @colorizedmind 😊 

we have released a new version of `wolkenkit-console`. Please run the following command to update this module: `npm install -g wolkenkit-console`.
A short feedback would be nice 🤔

**Comment by colorizedmind** [comment]
Thank you. Issue is fixed for my machine.
